# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          # The Flutter version to make available on the path
          flutter-version: '3.0.5'

      - name: Install flutter dependencies
        run: flutter pub get

  lint-checks:
    name: Check linting
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          # The Flutter version to make available on the path
          flutter-version: '3.0.5'

      - name: Install flutter dependencies
        run: flutter pub get
                
      - name: Analyze project source
        run: flutter analyze
